# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main1.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(975, 757)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("border: 5px solid;\n"
"border-color: rgb(0, 255, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.Encrypted = QtWidgets.QTextEdit(self.centralwidget)
        self.Encrypted.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        self.Encrypted.setFont(font)
        self.Encrypted.setStyleSheet("border: 5px solid;\n"
"border-color: rgb(0, 255, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.Encrypted.setReadOnly(True)
        self.Encrypted.setObjectName("Encrypted")
        self.verticalLayout.addWidget(self.Encrypted)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.label_Status = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Status.setFont(font)
        self.label_Status.setText("")
        self.label_Status.setObjectName("label_Status")
        self.gridLayout.addWidget(self.label_Status, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 975, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_5 = QtWidgets.QMenu(self.menu_2)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menu_5)
        self.menu_6.setObjectName("menu_6")
        self.menu_7 = QtWidgets.QMenu(self.menu_5)
        self.menu_7.setObjectName("menu_7")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_Create = QtWidgets.QAction(MainWindow)
        self.action_Create.setObjectName("action_Create")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setMenuRole(QtWidgets.QAction.QuitRole)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Create_enigma = QtWidgets.QAction(MainWindow)
        self.action_Create_enigma.setObjectName("action_Create_enigma")
        self.action_Conf_open = QtWidgets.QAction(MainWindow)
        self.action_Conf_open.setObjectName("action_Conf_open")
        self.action_Save_as = QtWidgets.QAction(MainWindow)
        self.action_Save_as.setObjectName("action_Save_as")
        self.action_Conf_save = QtWidgets.QAction(MainWindow)
        self.action_Conf_save.setObjectName("action_Conf_save")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setCheckable(True)
        self.action_3.setChecked(True)
        self.action_3.setObjectName("action_3")
        self.action_Choose_alphabet = QtWidgets.QAction(MainWindow)
        self.action_Choose_alphabet.setObjectName("action_Choose_alphabet")
        self.action_Add_alphabet = QtWidgets.QAction(MainWindow)
        self.action_Add_alphabet.setObjectName("action_Add_alphabet")
        self.action_Reflector_change = QtWidgets.QAction(MainWindow)
        self.action_Reflector_change.setObjectName("action_Reflector_change")
        self.action_Rotor1_change = QtWidgets.QAction(MainWindow)
        self.action_Rotor1_change.setObjectName("action_Rotor1_change")
        self.action_Rotor2_change = QtWidgets.QAction(MainWindow)
        self.action_Rotor2_change.setObjectName("action_Rotor2_change")
        self.action_Rotor3_change = QtWidgets.QAction(MainWindow)
        self.action_Rotor3_change.setObjectName("action_Rotor3_change")
        self.action_Q_plug_board = QtWidgets.QAction(MainWindow)
        self.action_Q_plug_board.setObjectName("action_Q_plug_board")
        self.action_Change_plug_board = QtWidgets.QAction(MainWindow)
        self.action_Change_plug_board.setObjectName("action_Change_plug_board")
        self.action_Help = QtWidgets.QAction(MainWindow)
        self.action_Help.setObjectName("action_Help")
        self.menu.addAction(self.action_Create)
        self.menu.addAction(self.action_Open)
        self.menu.addAction(self.action_Save)
        self.menu.addAction(self.action_Save_as)
        self.menu.addAction(self.action_Exit)
        self.menu_6.addAction(self.action_Rotor1_change)
        self.menu_6.addAction(self.action_Rotor2_change)
        self.menu_6.addAction(self.action_Rotor3_change)
        self.menu_7.addAction(self.action_Q_plug_board)
        self.menu_7.addAction(self.action_Change_plug_board)
        self.menu_5.addAction(self.menu_6.menuAction())
        self.menu_5.addAction(self.action_Reflector_change)
        self.menu_5.addAction(self.menu_7.menuAction())
        self.menu_2.addAction(self.action_Conf_open)
        self.menu_2.addAction(self.menu_5.menuAction())
        self.menu_2.addAction(self.action_Conf_save)
        self.menu_3.addAction(self.action_Help)
        self.menu_4.addAction(self.action_Choose_alphabet)
        self.menu_4.addAction(self.action_Add_alphabet)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EasyEncrypt"))
        self.label.setText(_translate("MainWindow", "Ввод:"))
        self.label_2.setText(_translate("MainWindow", "Зашифрованный текст:"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Конфигурация машины"))
        self.menu_5.setTitle(_translate("MainWindow", "Редактировать"))
        self.menu_6.setTitle(_translate("MainWindow", "Роторы"))
        self.menu_7.setTitle(_translate("MainWindow", "Коммутационная панель"))
        self.menu_3.setTitle(_translate("MainWindow", "Cправка"))
        self.menu_4.setTitle(_translate("MainWindow", "Алфавиты (beta)"))
        self.action_Open.setText(_translate("MainWindow", "Открыть"))
        self.action_Save.setText(_translate("MainWindow", "Сохранить"))
        self.action_Create.setText(_translate("MainWindow", "Создать"))
        self.action_Create.setToolTip(_translate("MainWindow", "Новый"))
        self.action_Exit.setText(_translate("MainWindow", "Выход"))
        self.action_Create_enigma.setText(_translate("MainWindow", "Создать"))
        self.action_Conf_open.setText(_translate("MainWindow", "Открыть"))
        self.action_Save_as.setText(_translate("MainWindow", "Сохранить как"))
        self.action_Conf_save.setText(_translate("MainWindow", "Сохранить"))
        self.action_2.setText(_translate("MainWindow", "Русский"))
        self.action_3.setText(_translate("MainWindow", "Английский"))
        self.action_Choose_alphabet.setText(_translate("MainWindow", "Выбрать"))
        self.action_Add_alphabet.setText(_translate("MainWindow", "Добавить новый"))
        self.action_Reflector_change.setText(_translate("MainWindow", "Рефлектор"))
        self.action_Rotor1_change.setText(_translate("MainWindow", "Ротор 1"))
        self.action_Rotor2_change.setText(_translate("MainWindow", "Ротор 2"))
        self.action_Rotor3_change.setText(_translate("MainWindow", "Ротор 3"))
        self.action_Q_plug_board.setText(_translate("MainWindow", "Количество подключений"))
        self.action_Change_plug_board.setText(_translate("MainWindow", "Подключения"))
        self.action_Help.setText(_translate("MainWindow", "Посмотреть справку"))
